# Generated by Django 3.2.3 on 2021-06-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpost',
            name='how_to_reach',
        ),
    ]
